name: invoice_management_system
description: "Invoice generator and management system"
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.2
  screen_retriever: ^0.2.2
  shared_preferences: ^2.5.5
  path_provider: ^2.1.6
  path: ^1.9.1
  sqlite3: ^3.5.0
  sqlite3_flutter_libs: ^0.6.0+eol
  file_picker: '>=10.3.7 <11.0.0'
  google_fonts: ^8.2.0
  pdf: ^3.13.0
  liquid_glass_widgets: ^0.23.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Poppins-Regular.ttf
    - assets/fonts/Poppins-Bold.ttf
